% verstion - 1.0
% Decenteralized Vaccination Program

function [png] = Decentralized_Vaccination_pn_pdf()
% t1 = Visit
% t2 = Vaccine
% t3 = Done

png.PN_name = 'Decenteralized Vaccination Program';
png.set_of_Ps = {'p1','p2','p3','p4','p5','p6','p7'}
% Done
png.set_of_Ts = {'visit', 'vaccine'}
png.set_of_As = {
    'p1','visit',1,...
    'p2','visit',2,...
    'p3','visit',1,...
    'p4','vaccine',1,...
    'visit','p5',1,...
    'visit','p6',2,...
    'p5','vaccine',1,...
    'p6','vaccine',2,...
    'vaccine','p2',2,...
    'vaccine','p3',1,...
    'vaccine', 'p7',1,...
    % we have to fix the vehichles tokens, it's enable after to run
    
    }
end

%'p4','Vaccine',1,...
%'p5','Vaccine',1,...
%'p6','Vaccine',2,...
%'Visit','p5',1,...
%'Visit','p6',2,...
%'Vaccine','p7',1,...
%'Vaccine','p2',1,...