% PDF: Centeralized Vaccination Program

function [png] = Centralized_Vaccination_pn_pdf()
png.PN_name = 'Centeralized Vaccination Program';
png.set_of_Ps = {'p1','p2','p3','p4','p5'}
png.set_of_Ts = {'tVISITOR', 'tREGISTRATION', 'tVACCINATION', 'tWAITING'}
png.set_of_As = {
    'tVISITOR','p1',5,...
    'p1','tREGISTRATION',1,...
    'tREGISTRATION','p2',1,...
    'p2','tVACCINATION',1,...
    'p5','tVACCINATION',1,...
    'tVACCINATION','p3',1,...
    'p3','tWAITING',1,...
    'tWAITING','p4',1,...
    }
end
