% PDF: Centeralized Vaccination Program

function [png] = Centralized_Vaccination_pn_pdf()
png.PN_name = 'Centeralized Vaccination Program';
png.set_of_Ps = {'p1','p2','p3','p4','p5'}
png.set_of_Ts = {'tVISITOR', 'tREGISTRATION', 'tVACCINATION', 'tWAITING'}
png.set_of_As = {
    'tVISITOR','p1',1,...
    'p1','tREGISTRATION',12,...
    'tREGISTRATION','p2',12,...
    'p2','tVACCINATION',24,...
    'p5','tVACCINATION',24,...
    'tVACCINATION','p3',24,...
    'p3','tWAITING',30,...
    'tWAITING','p4',30,...
    }
end

