% verstion - 1.0
% Centeralized Vaccination Program

function [png] = Centralized_Vaccination_pn_pdf()
% t1 = Registration
% t2 = Vaccine
% t3 = Wait 
png.PN_name = 'Centeralized Vaccination Program';
png.set_of_Ps = {'p1','p2','p3','p4','p5','p6','p7','p8'}
png.set_of_Ts = {'Registration', 'Vaccine', 'Wait'}
png.set_of_As = {
    'p1','Registration',10,...
    'p2','Registration',10,...
    'p3','Vaccine',10,...
    'p4','Vaccine',10,...
    'p5','Vaccine',10,...
    'p6','Wait',10,...
    'p7','Wait',10,...
    'Registration','p2',10,...
    'Registration','p3',10,...
    'Vaccine','p5',10,...
    'Vaccine','p6',10,...
    'Wait','p7',10,...
    'Wait','p8',10,...
    }
end

