% PDF: Centeralized Vaccination Program

function [png] = Centralized_Vaccination_pn_pdf()
png.PN_name = 'Centeralized Vaccination Program';
png.set_of_Ps = {'p1','p2','p3','p4','p5'}
png.set_of_Ts = {'tREGISTRATION', 'tVACCINATION', 'tWAITING'}
png.set_of_As = {
    'p1','tREGISTRATION',15,...
    'tREGISTRATION','p2',15,...
    'p2','tVACCINATION',15,...
    'p5','tVACCINATION',15,...
    'tVACCINATION','p3',15,...
    'p3','tWAITING',15,...
    'tWAITING','p4',15,...
    }
end

