% PDF: Decenteralized Vaccination Program

function [png] = Decentralized_Vaccination_pn_pdf()
    
    global global_info
    
    png.PN_name = 'Decenteralized Vaccination Program';
    png.set_of_Ps = {'p1','p2','p3','p4','p5','p6','p7','p8'}
    png.set_of_Ts = {'tDRIVE', 'tVACCINATION', 'tCOMPLETION'}
    png.set_of_As = {
        'p1','tDRIVE',2,...
        'p2','tDRIVE',1,...
        'p3','tDRIVE',1,...
        'tDRIVE','p4',2,...
        'tDRIVE','p5',global_info.residents_per_street,...
        'p4','tVACCINATION',1,...
        'p5','tVACCINATION',1,...
        'p6','tVACCINATION',1,...
        'tVACCINATION','p4',1,...
        'tVACCINATION','p7',1,...
        'p4','tCOMPLETION',2,...
        'p7','tCOMPLETION',global_info.residents_per_street,...
        'tCOMPLETION','p1',2,...
        'tCOMPLETION','p3',1,...
        'tCOMPLETION','p8',global_info.residents_per_street,...
    }
end