% PDF: Centeralized Vaccination Program

function [png] = Centralized_Vaccination_pn_pdf()
png.PN_name = 'Centeralized Vaccination Program';

png.set_of_Ps = {'p1','p2','p3','p4','p5'};

global global_info

png.set_of_Ts = construct('transitions',...
    global_info.num_of_staff,...
    global_info.num_of_health_workers,...
    global_info.num_of_waiting_rooms...
);

png.set_of_As = construct('arches',...
    global_info.num_of_staff,...
    global_info.num_of_health_workers,...
    global_info.num_of_waiting_rooms...
);
end

